#!/bin/bash

# Copyright (C) by Sakaki, 2026.
# License: GNU General Public License version 3 <https://www.gnu.org/licenses/gpl-3.0.en.html>

MAYA_VERSION=3
MAYA_TREE=/usr/local/share/maya

function rootCheck(){
	[[ $EUID != 0 ]] && printf "\e[0;91merror:\e[0m you can't run this without root access.\n" && exit
}

function cleaning(){
    if [[ -d /tmp/maya ]]; then
        rm -rf /tmp/maya
    fi
    mkdir -p /tmp/maya
}

function binaryExCheck(){
    if [[ ! -f "$MAYA_TREE/pkg/$1" ]]; then
        printf "\e[0;91merror:\e[0m the \e[1m'$1'\e[0m does not exist.\n" && exit
    fi
}

function dependencieCheck(){
	if [[ ! -z $DEPENDENCIES ]]; then
        for deps in "${DEPENDENCIES[@]}"; do
            if ! command -v $deps; then
                printf "\e[0;91merror:\e[0m the \e[1m'$deps'\e[0m does not exist.\n" && exit
            fi
        done
    fi
}

case $1 in
	"--help"|"-h")
        printf "\033[4moperations:\033[0m\n"
        printf "%-35s %0s\n" " -in, --install" "install a package."
        printf "%-35s %0s\n" " -rm, --remove" "remove a package."
        printf "%-35s %0s\n" " -sy, --sync" "this synchronizes maya and recipes."
        printf "%-35s %0s\n" " -rs, --register-sync" "it scans installed packages for orphaned packages/records."
	    printf "%-35s %0s\n" " -l,  --list" "shows all available packages for installation."
        printf "\e[2m%-35s\e[0m %0s\n" "      --list <package>" "filters the available packages for installation."
        printf "%-35s %0s\n" " -li, --list-installed" "list all installed packages."
        printf "\e[2m%-35s\e[0m %0s\n" "      --list-installed <package>" "filters all installed packages."
        printf "\n%-35s %0s\n" " -h, --help" "show this message."
	    printf "%-35s %0s\n" " -v, --version" "shows the version."
        printf "\n\e[1mReport bugs to: https://github.com/sakaki91/maya\e[0m\n\n"
    ;;
    "--version"|"-v") printf "maya $MAYA_VERSION\nCopyright (C) by Sakaki, 2026.\nLicense: GNU General Public License version 3 <https://www.gnu.org/licenses/gpl-3.0.en.html>\n" ;;
    "--list"|"-l")
        if [[ -z $2 ]]; then
            for ALLPACKAGES in /usr/local/share/maya/pkg/*; do
                ALL_PKG="$(basename $ALLPACKAGES)"
                . "$MAYA_TREE/pkg/$ALL_PKG"
                printf "%-15s %0s\n" "$NAME" "$DESCRIPTION"
            done
        else
            binaryExCheck "$2"
            . "$MAYA_TREE/pkg/$2"
            printf "%-15s %0s\n" "$NAME" "$DESCRIPTION"
        fi
    ;;
 	"--list-installed"|"-li")
        if [[ ! $(ls $MAYA_TREE/pkg/.info/) ]]; then
            printf "\e[0;91merror:\e[0m no packages installed.\n" && exit
        else
            for INSTALLEDPACKAGES in /usr/local/share/maya/pkg/.info/*; do
                ALL_IN_PKG="$(basename $INSTALLEDPACKAGES)"
                . "$MAYA_TREE/pkg/$ALL_IN_PKG"
                printf "%-15s %0s\n" "$NAME" "$DESCRIPTION"
            done
        fi
    ;;
	"--sync"|"-sy")
        rootCheck ; cleaning
        git clone https://github.com/sakaki91/maya /tmp/maya/maya.source
        /usr/bin/install /tmp/maya/maya.source/maya /usr/local/bin/maya ; /usr/bin/install /tmp/maya/maya.source/{README,LICENSE} /usr/local/share/maya/doc/
        cp -r /tmp/maya/maya.source/{pkg,src} /usr/local/share/maya
	;;
    "--install"|"-in")
		binaryExCheck "$2" ; rootCheck ; cleaning
		mkdir -p /tmp/maya ; source "$MAYA_TREE/pkg/$2"
		dependencieCheck ; install ; echo "INSTALLED_VERSION=$VERSION" > "$MAYA_TREE/pkg/.info/$NAME"
	;;
    "--remove"|"-rm")
		binaryExCheck "$2" ; rootCheck
        if [[ $(command -v $2) ]]; then
            if [[ -f $MAYA_TREE/pkg/.info/$2 ]]; then
                rm -f $MAYA_TREE/pkg/.info/$2 ; source "$MAYA_TREE/pkg/$2" ; remove
            fi
        elif [[ ! $(command -v $2) ]]; then
            if [[ -f $MAYA_TREE/pkg/.info/$2 ]]; then
                rm -f $MAYA_TREE/pkg/.info/$2
            fi
        fi  
    ;;
    "--register-sync"|"-rs")
        if [[ ! $(ls $MAYA_TREE/pkg/.info ) ]]; then
            printf "\e[0;91merror:\e[0m no packages installed.\n" && exit
        fi
        for registerInfo in $MAYA_TREE/pkg/.info/*; do
            PRESENT_BINARY=$(basename $registerInfo)
            if ! command -v $PRESENT_BINARY &>> /dev/null; then
                printf "%-20s\033[1;91m%0s\033[0m\n" "$PRESENT_BINARY." "[ orphan package ]" 
            fi
            if command -v $PRESENT_BINARY &>> /dev/null; then
                printf "%-20s\033[1;92m%0s\033[0m\n" "$PRESENT_BINARY." "[ ok ]"
            fi
        done
    ;;
    *) printf "usage: maya <operation>\n" ;;
esac