#!/bin/bash

NAME="atl"
VERSION="git"
DESCRIPTION="small system fetch."
SOURCE="https://github.com/sakaki91/about-this-linux"
TYPE="system"
DEPENDENCIES=(
	"git"
)

function install(){
    git clone $SOURCE /tmp/maya/$NAME
    /usr/bin/install /tmp/maya/$NAME/$NAME /usr/local/bin/$NAME
}

function remove(){
    rm -f /usr/local/bin/$NAME
}
