#!/bin/bash

NAME="cbonsai"
VERSION="latest"
DESCRIPTION="grow bonsai trees in your terminal."
SOURCE="https://gitlab.com/jallbrit/$NAME"
DEPENDENCIES=(
	"gcc"
	"make"
	"git"
)

function install(){
    	git clone $SOURCE /tmp/maya/$NAME
    	(cd /tmp/maya/$NAME && make install)
}

function remove(){
    	rm -f /usr/local/bin/cbonsai
    	rm -f /usr/local/share/bash-completion/completions/cbonsai
}
