#!/bin/bash

NAME="discord"
VERSION="1.0.149"
DESCRIPTION="All-in-one voice and text chat for gamers that's free, secure, and works on both your desktop and phone."
SOURCE="https://stable.dl2.discordapp.net/apps/linux/$VERSION/$NAME-$VERSION.tar.gz"
DEPENDENCIES=(
    "wget"
    "tar"
)

function install(){
    wget -c $SOURCE --directory-prefix=/tmp/maya/$NAME
    tar -xvf /tmp/maya/$NAME/$NAME-$VERSION.tar.gz --directory=/tmp/maya/$NAME
    sudo cp /tmp/maya/$NAME/Discord/discord /usr/bin/discord
    sudo cp /tmp/maya/$NAME/Discord/discord.desktop /usr/share/applications/discord.desktop
    sudo cp /tmp/maya/$NAME/Discord/discord.png /usr/local/share/icons/hicolor/scalable/apps/discord.png
}

function remove(){
    sudo rm -f /usr/bin/discord
    sudo rm -f /usr/share/applications/discord.desktop
    sudo rm -f /usr/local/share/icons/hicolor/scalable/apps/discord.png
}