#!/bin/bash

NAME="fastfetch"
VERSION="git"
DESCRIPTION="A maintained, feature-rich and performance oriented, neofetch like system information tool."
SOURCE="https://github.com/$NAME-cli/$NAME"
DEPENDENCIES=(
	"cmake"
    "gcc"
    "git"
)

function install(){
	git clone $SOURCE /tmp/maya/$NAME
    (
       	cd /tmp/maya/$NAME
       	./run.sh
       	/usr/bin/install /tmp/maya/$NAME/build/$NAME /usr/local/bin/$NAME
    )
}

function remove(){
	rm -f /usr/local/bin/$NAME
}
