#!/bin/bash
# INCOMPLETO.

NAME="gcc"
VERSION="git"
SOURCE="git://gcc.gnu.org/git/gcc.git"

function install(){
    git clone $SOURCE /tmp/$NAME
    (
        cd /tmp/$NAME
        ./contrib/download_prerequisites
        mkdir objdir && objdir
        ../configure --enable-languages=c,c++ --disable-multilib
    )
}

function remove(){
    
}

