#!/bin/bash

NAME="minecraft"
VERSION="latest"
DESCRIPTION="Minecraft Java (Official Launcher)"
SOURCE="https://launcher.mojang.com/download/Minecraft.tar.gz"
DEPENDENCIES=(
	"wget"
	"tar"
)

function install(){
	wget -c $SOURCE --directory-prefix=/tmp/maya/$NAME
    	tar -xvf /tmp/maya/$NAME/Minecraft.tar.gz --directory=/tmp/maya/$NAME
   	/usr/bin/install /tmp/maya/$NAME/$NAME-launcher/$NAME-launcher /usr/local/bin/$NAME-launcher
}

function remove(){
	rm -f /usr/local/bin/$NAME-launcher
}
