#!/bin/bash

NAME="neofetch"
VERSION="git"
DESCRIPTION="A command-line system information tool written in bash 3.2+"
SOURCE="https://github.com/dylanaraps/neofetch"
TYPE="system"
DEPENDENCIES=(
	"git"
)

function install(){
    git clone $SOURCE /tmp/maya/$NAME
    /usr/bin/install /tmp/maya/$NAME/$NAME /usr/local/bin/$NAME
}

function remove(){
	rm -f /usr/local/bin/$NAME
}
