#!/bin/bash

NAME="neofetch"
VERSION="7.0.1"
DESCRIPTION="A command-line system information tool written in bash 3.2+"
SOURCE="https://github.com/dylanaraps/neofetch"

function install(){
    git clone $SOURCE /tmp/maya/$NAME
    sudo cp /tmp/maya/$NAME/$NAME /usr/bin/$NAME
}

function remove(){
    sudo rm -rf /bin/$NAME "$MAYA_TMP/$NAME"
}