#!/bin/bash

NAME="onefetch"
VERSION="git"
DESCRIPTION="Command-line Git information tool."
SOURCE="https://github.com/o2sh/onefetch"
TYPE="system"
DEPENDENCIES=(
    "git"
    "cargo"
)

function install(){
    git clone $SOURCE /tmp/maya/$NAME
    (
        cd /tmp/maya/$NAME
        cargo build --release --features=fail-on-deprecated
        /usr/bin/install /tmp/maya/$NAME/target/release/onefetch /usr/local/bin/$NAME
    )
}

function remove(){
    rm -f /usr/local/bin/$NAME
}
