#!/bin/bash

NAME="pfetch"
VERSION="git-0.6.0"
SOURCE='https://github.com/dylanaraps/pfetch'

function install(){
    git clone $SOURCE /tmp/$NAME
    sudo cp -r /tmp/$NAME/$NAME /bin/$NAME
}

function remove(){
    sudo rm -f /bin/$NAME
}