#!/bin/bash

NAME="pfetch"
VERSION="git"
DESCRIPTION="A pretty system information tool written in POSIX sh."
SOURCE='https://github.com/dylanaraps/pfetch'
DEPENDENCIES=(
	"git"
)

function install(){
   	git clone $SOURCE /tmp/maya/$NAME
	/usr/bin/install /tmp/maya/$NAME/$NAME /usr/bin/$NAME
}

function remove(){
	rm -rf /bin/$NAME "$MAYA_TMP/$NAME"
}