#!/bin/bash

NAME="ren"
VERSION="v1.0"
DESCRIPTION="small system fetch."
SOURCE="https://github.com/sakaki91/ren"

function install(){
    git clone $SOURCE /tmp/maya/$NAME
    sudo cp /tmp/maya/$NAME /usr/local/bin/$NAME
}

function remove(){
    rm -f /usr/local/bin/$NAME
}